import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const ubuntu = localFont({
  src: [
    { path: './fonts/Ubuntu-Th.ttf', weight: '200' },
    { path: './fonts/Ubuntu-L.ttf', weight: '300' },
    { path: './fonts/Ubuntu-LI.ttf', style: 'italic', weight: '300' },
    { path: './fonts/Ubuntu-R.ttf', weight: '400' },
    { path: './fonts/Ubuntu-RI.ttf', style: 'italic', weight: '400' },
    { path: './fonts/Ubuntu-M.ttf', weight: '500' },
    { path: './fonts/Ubuntu-MI.ttf', style: 'italic', weight: '500' },
    { path: './fonts/Ubuntu-B.ttf', weight: '700' },
    { path: './fonts/Ubuntu-BI.ttf', style: 'italic', weight: '700' },
  ],
  variable: '--font-ubuntu',
});

const ubuntuCondensed = localFont({
  src: [{ path: './fonts/Ubuntu-C.ttf', weight: '400' }],
  variable: '--font-ubuntu-condensed',
});

const ubuntuMono = localFont({
  src: [
    { path: './fonts/UbuntuMono-R.ttf', weight: '400' },
    { path: './fonts/UbuntuMono-RI.ttf', style: 'italic', weight: '400' },
    { path: './fonts/UbuntuMono-B.ttf', weight: '700' },
    { path: './fonts/UbuntuMono-BI.ttf', style: 'italic', weight: '700' },
  ],
  variable: '--font-ubuntu-mono',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ubuntu.variable} ${ubuntuCondensed.variable} ${ubuntu.variable}`}>
      <body className="bg-neutral-50 dark:bg-primary">{children}</body>
    </html>
  );
}
