// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en":    &dictionary{index: enIndex, data: enData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Successfully deleted %d files\n":      1,
	"Successfully deleted %d redis keys\n": 0,
}

var enIndex = []uint32{ // 3 elements
	0x00000000, 0x00000057, 0x000000a4,
} // Size: 36 bytes

const enData string = "" + // Size: 164 bytes
	"\x04\x00\x01\x0aR\x14\x01\x81\x01\x00\x02#\x02Successfully deleted one r" +
	"edis key\x00&\x02Successfully deleted %[1]d redis keys\x04\x00\x01\x0aH" +
	"\x14\x01\x81\x01\x00\x02\x1e\x02Successfully deleted one file\x00!\x02Su" +
	"ccessfully deleted %[1]d files"

var en_USIndex = []uint32{ // 3 elements
	0x00000000, 0x0000002b, 0x00000051,
} // Size: 36 bytes

const en_USData string = "" + // Size: 81 bytes
	"\x04\x00\x01\x0a&\x02Successfully deleted %[1]d redis keys\x04\x00\x01" +
	"\x0a!\x02Successfully deleted %[1]d files"

	// Total table size 317 bytes (0KiB); checksum: AE612C7F
